name: Deploy Content to lawnew [3583ecf1-3bb1-4017-8b43-a640b45e95ca]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-3583ecf1-3bb1-4017-8b43-a640b45e95ca.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-3583ecf1-3bb1-4017-8b43-a640b45e95ca.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'socnrg1'
      workspaceName: 'lawnew'
      workspaceId: '2b185445-7361-40b3-afe4-411323573e4a'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,AutomationRule,HuntingQuery,Parser,Playbook,Workbook,Watchlist'
      branch: 'main'
      sourceControlId: '3583ecf1-3bb1-4017-8b43-a640b45e95ca'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_3583ecf13bb140178b43a640b45e95ca }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_3583ecf13bb140178b43a640b45e95ca }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_3583ecf13bb140178b43a640b45e95ca }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_3583ecf13bb140178b43a640b45e95ca }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_3583ecf13bb140178b43a640b45e95ca }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_3583ecf13bb140178b43a640b45e95ca }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_3583ecf13bb140178b43a640b45e95ca }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_3583ecf13bb140178b43a640b45e95ca }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_3583ecf13bb140178b43a640b45e95ca }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-3583ecf1-3bb1-4017-8b43-a640b45e95ca.ps1